# Generated by Django 3.1.5 on 2021-09-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('house_number', models.CharField(max_length=5)),
                ('problem', models.CharField(max_length=300)),
                ('completed', models.BooleanField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.worker')),
            ],
        ),
    ]
